version: '3.7'
services:
  web:
    build: .
    ports:
      - '5000:5000'
    env_file:
      - .env
    volumes:
      - ./database:/usr/src/app/database
      - ./src:/usr/src/app
  proxy:
    image: 'abiosoft/caddy-docker'
    build:
      context: github.com/abiosoft/caddy-docker.git
      args:
        PLUGINS: 'http.login,http.jwt'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/Caddyfile
    env_file:
      - .env
